name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.0.1/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/
      - name: Run
        run: ktlint --reporter sarif -l none > ktlint.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ktlint.sarif
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run
        run: |
          chmod +x gradlew
          ./gradlew detekt
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
      - name: Job Summary
        if: success() || failure()
        run: cat ./app/build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run
        run: |
          chmod +x gradlew
          ./gradlew build
